name: common-test deploy

on:
  push:
    branches: master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Maven package deploy
      env:
        USER_NAME: ${{ github.actor }}
        TOKEN: ${{ secrets.TOKEN }}
      run: mvn -s .github/settings.xml dependency:go-offline package deploy

